spring:
  profiles:
    active: dev

jwt:
  secret: aiksjfdalkADKFAJE3455ALKDANREBBCCCEIARAHAHAHKHE3DJADKJVHNFKHFUGRYRBFBKJEHFGAABCCHH44455KLJAKDAJAJ
  accessTokenExpireLengthInMinutes: 10
  refreshTokenExpireLengthInMinutes: 10





