server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/orderneat
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  config:
    activate:
      on-profile: dev
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

name: oe-dev
environment: development
enabled: false
servers: localhost:8080
